Fail with permanent error if multiple records are found
The standard is clear that multiple valid records should cause a permanent
error: https://tools.ietf.org/html/rfc7208#section-4.5

Today the library just picks the first one, resulting in unpredictable
and non-standard behaviour.

This patch fixes that by enforcing a single valid record exists.

Found by the standard test suite.